/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio;

import java.awt.Point;
import java.util.ArrayList;

/**
 *
 * @author 57319
 */
public class FrmVB extends javax.swing.JFrame {

    String titulo = "Abrir archivo";
    String titulobtn = "Seleccionar";
    String filtro = ".pdf";
    String descripcion = "PDF";

    int x1, y1, x2, y2;
    
    Metodos m = new Metodos();
    

    String activador = "Linea";
    
    
    String[] lineas = new String[5];

    public FrmVB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        ComboBox = new javax.swing.JComboBox<>();
        jToolBar2 = new javax.swing.JToolBar();
        BtnSeleccionar = new javax.swing.JButton();
        BtnAbrir = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPanel.setBackground(new java.awt.Color(0, 0, 0));
        pnlPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlPanelLayout = new javax.swing.GroupLayout(pnlPanel);
        pnlPanel.setLayout(pnlPanelLayout);
        pnlPanelLayout.setHorizontalGroup(
            pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPanelLayout.setVerticalGroup(
            pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        ComboBox.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Linea", "Circulo", "Rectangulo" }));
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });
        jToolBar1.add(ComboBox);

        jToolBar2.setRollover(true);

        BtnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenpng/Cursor.jpg"))); // NOI18N
        BtnSeleccionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSeleccionar.setMaximumSize(new java.awt.Dimension(50, 50));
        BtnSeleccionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionarActionPerformed(evt);
            }
        });
        jToolBar2.add(BtnSeleccionar);

        BtnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenpng/carpeta.jpg"))); // NOI18N
        BtnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAbrirActionPerformed(evt);
            }
        });
        jToolBar2.add(BtnAbrir);

        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenpng/guardar.png"))); // NOI18N
        BtnGuardar.setFocusable(false);
        BtnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        jToolBar2.add(BtnGuardar);

        jLabel1.setText("Seleccionar  ");

        jLabel2.setText("Abrir");

        jLabel3.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)))
                        .addGap(0, 175, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        activador = ComboBox.getSelectedItem().toString();
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void BtnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionarActionPerformed

    }//GEN-LAST:event_BtnSeleccionarActionPerformed

    private void BtnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAbrirActionPerformed

        String elegirArchivo = Archivo.elegirArchivo(titulo, titulobtn, filtro, descripcion);
        String texto = Archivo.obtenerTextoArchivo(Archivo.abrirArchivo(elegirArchivo));
        System.out.println(texto);

    }//GEN-LAST:event_BtnAbrirActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        
        
        
        Archivo.guardarArchivo("Intento #1", lineas);
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void pnlPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPanelMouseClicked


    }//GEN-LAST:event_pnlPanelMouseClicked

    private void pnlPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPanelMousePressed

        x1 = evt.getX();
        y1 = evt.getY();

    }//GEN-LAST:event_pnlPanelMousePressed

    private void pnlPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPanelMouseReleased
        x2 = evt.getX();
        y2 = evt.getY();

        switch (activador){
            case "Linea" :
                if(x1 == x2 && y1 == y2){
                    
                }
                else{
                    Graficas.Linea(pnlPanel.getGraphics(), x1, y1, x2, y2);
                }
                break;
                
            case "Circulo" :
                if(x1 == x2 && y1 == y2){
                    
                }
                else{
                    Graficas.Circulo(pnlPanel.getGraphics(), x1, y1, x2/4, y2/4);
                }
                break;
                
            case "Rectangulo":
                if(x1 == x2 && y1 == y2){
                    
                }
                else{
                    Graficas.Rectangulo(pnlPanel.getGraphics(), x1/2, y1/2, x2/2, y2/2);
                }
                break;
                
        }
        Nodo n = new Nodo(activador, x1, y1, x2, y2);
        m.agregar(n);
        lineas[0] = n.getTipo();
        lineas[1] = String.valueOf(n.getX1());
        lineas[2] = String.valueOf(n.getY1());
        lineas[3] = String.valueOf(n.getX2());
        lineas[4] = String.valueOf(n.getY2());

    }//GEN-LAST:event_pnlPanelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAbrir;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnSeleccionar;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JPanel pnlPanel;
    // End of variables declaration//GEN-END:variables
}
